"""
FastAPI Application Main Entry Point
"""

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.encoders import jsonable_encoder
from contextlib import asynccontextmanager
import uvicorn
from pathlib import Path

# Import routers
from src.api.routers import trends, segments, predictions, anomalies, summary, recommendations
from src.api.models.schemas import HealthCheck, ErrorResponse
from src.api.utils.data_loader import data_loader

# ============================
# Application Metadata
# ============================
API_VERSION = "1.0.0"
API_TITLE = "User Behavior Insights API"
API_DESCRIPTION = """
API for accessing user behavior insights, trends, predictions, and anomalies.

## Features

* **Trends**: Daily and weekly user behavior trends
* **Segments**: User segment performance and insights
* **Predictions**: ML model predictions for conversions and bounces
* **Anomalies**: Anomaly detection and alerts
* **Summary**: LLM-generated insights and recommendations

## Data Sources

This API serves data generated by:
- `daily_trends.py` - Daily aggregated metrics
- `weekly_trends.py` - Weekly aggregated metrics
- `segment_insights.py` - Segment performance trends
- `ml_insights.py` - ML model predictions
- `anomaly_detection.py` - Anomaly detection results
- `llm_summaries.py` - AI-generated summaries
"""


# ============================
# Lifespan Events
# ============================
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan events"""
    # Startup
    print("=" * 60)
    print("Starting User Behavior Insights API")
    print("=" * 60)
    print(f"API Version: {API_VERSION}")
    print(f"Data directory: {Path(__file__).parent.parent.parent / 'data'}")
    print("=" * 60)
    
    yield
    
    # Shutdown
    print("\nShutting down API...")
    data_loader.clear_cache()
    print("Cache cleared.")


# ============================
# FastAPI Application
# ============================
app = FastAPI(
    title=API_TITLE,
    description=API_DESCRIPTION,
    version=API_VERSION,
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json"
)

# ============================
# CORS Middleware
# ============================
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, specify allowed origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================
# Exception Handlers
# ============================
@app.exception_handler(404)
async def not_found_handler(request: Request, exc):
    """Handle 404 errors"""
    return JSONResponse(
        status_code=404,
        content=jsonable_encoder(
            ErrorResponse(
                error="Not Found",
                detail=f"The requested resource was not found: {request.url.path}"
            )
        ),
    )


@app.exception_handler(500)
async def internal_error_handler(request: Request, exc):
    """Handle 500 errors"""
    return JSONResponse(
        status_code=500,
        content=jsonable_encoder(
            ErrorResponse(
                error="Internal Server Error",
                detail="An unexpected error occurred. Please check the logs."
            )
        ),
    )


# ============================
# Include Routers
# ============================
# All routes are prefixed with /api
app.include_router(trends.router, prefix="/api")
app.include_router(segments.router, prefix="/api")
app.include_router(predictions.router, prefix="/api")
app.include_router(anomalies.router, prefix="/api")
app.include_router(summary.router, prefix="/api")
app.include_router(recommendations.router, prefix="/api")


# ============================
# Root Endpoints
# ============================
@app.get("/", response_model=HealthCheck, tags=["Health"])
async def root():
    """
    Root endpoint - API health check
    """
    return HealthCheck()


@app.get("/health", response_model=HealthCheck, tags=["Health"])
async def health_check():
    """
    Health check endpoint
    
    Returns API status and version information
    """
    return HealthCheck()


@app.get("/api/info")
async def api_info():
    """
    API information endpoint
    
    Returns API metadata and available endpoints
    """
    return {
        "name": API_TITLE,
        "version": API_VERSION,
        "endpoints": {
            "trends": {
                "daily": "/api/trends/daily",
                "weekly": "/api/trends/weekly",
                "summary": "/api/trends/daily/summary"
            },
            "segments": {
                "trends": "/api/segments/trends",
                "list": "/api/segments/list",
                "summary": "/api/segments/summary"
            },
            "predictions": {
                "segments": "/api/predictions/segments",
                "high_value": "/api/predictions/high-value/{model}",
                "at_risk": "/api/predictions/at-risk",
                "summary": "/api/predictions/summary"
            },
            "anomalies": {
                "list": "/api/anomalies",
                "summary": "/api/anomalies/summary",
                "recent": "/api/anomalies/recent"
            },
            "summary": {
                "llm": "/api/summary/llm"
            }
        },
        "documentation": {
            "swagger": "/docs",
            "redoc": "/redoc",
            "openapi": "/openapi.json"
        }
    }


# ============================
# Run Application
# ============================
if __name__ == "__main__":
    uvicorn.run(
        "src.api.main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info"
    )

